@startuml
'!include ./style.iuml
skinparam linetype ortho
skinparam linetype polyline

title Medication Prescription and Dispense - Actors and Transactions - Prescription
agent "  [[actors_and_transactions.html#order-placer Medication\nOrder Placer ]]" as orderplacer 
agent " [[actors_and_transactions.html#order-receiver Medication\nOrder Receiver ]]" as orderreceiver 
agent " [[actors_and_transactions.html#order-receiver Medication\nOrder Responder ]]" as orderresponder 
agent " [[actors_and_transactions.html#OrderConsumer Medication\nOrder Consumer   ]]" as OrderConsumer 


'agent "[[actors_and_transactions.html#dipensereceiver Dispense Receiver]]" as dispensereceiver
'agent "[[actors_and_transactions.html#dipenseresponder Dispense Responder]]" as dispenseresponder 



orderplacer -d- orderreceiver : "   [[pharm-5.html PHARM-5\nSubmit Medication Order]] ↓       "
orderreceiver -[hidden]r- orderresponder : "\t\t\t "

'orderresponder -d[hidden]- dispensereceiver
'orderresponder -r[hidden]- dispensereceiver
orderresponder -[hidden]r- OrderConsumer

orderplacer -[hidden]r- OrderConsumer : "\t\t\t  "

'dispensereceiver -l[hidden]- dispenseresponder : "   "


orderresponder -u- OrderConsumer: "   [[pharm-7.html PHARM-7\nRetrieve Medication Orders]] ↓          "

' → ↑ ← ↓

' dispensereceiver -r- dispenseresponder : ""



@enduml