@startuml
skinparam linetype ortho
skinparam linetype polyline

title Medication Actors \n Central Prescription Repository architecture\n


Package "Central Prescription Repository" {
agent "  [[actors-transactions.html#order-placer Order Placer ]]\n(e.g. GP system)" as orderplacer 
agent " [[actors-transactions.html#order-receiver Order Receiver ]]" as orderreceiver 
agent " [[actors-transactions.html#order-receiver Order Responder ]]" as orderresponder 
}
agent "[[actors-transactions.html#OrderConsumer Order Consumer  ]]\n (e.g. Pharmacy)" as OrderConsumer 


'agent "[[actors_and_transactions.html#dipensereceiver Dispense Receiver]]" as dispensereceiver
'agent "[[actors_and_transactions.html#dipenseresponder Dispense Responder]]" as dispenseresponder 


orderplacer -r- orderreceiver : " "
orderreceiver -[hidden]r-> orderresponder :" "



orderresponder -r- OrderConsumer: " "


@enduml