@startuml
'!include ./style.iuml
skinparam linetype ortho
skinparam linetype polyline

title Medication Prescription and Dispense - Actors and Transactions - Dispense
'agent "  [[actors-transactions.html#order-placer Order Placer ]]" as orderplacer 
'agent " [[actors-transactions.html#order-receiver Order Receiver ]]" as orderreceiver 
'agent " [[actors-transactions.html#order-receiver Order Responder ]]" as orderresponder 

agent " [[actors-transactions.html#dispense-reporter Medication\nDispense Reporter  ]]" as OrderConsumer 
agent " [[actors-transactions.html#dispense-consumer Medication\nDispense Consumer  ]]" as dispenseconsumer 
agent "[[actors-transactions.html#dispense-receiver Medication\nDispense Receiver]]" as dispensereceiver
agent "[[actors-transactions.html#dispense-responder Medication\nDispense Responder]]" as dispenseresponder 

dispenseconsumer -d- dispenseresponder : "   [[pharm-9.html PHARM-9\nRetrieve Dispense]] ↓       "


'orderreceiver -r[hidden]- orderresponder : "\t\t\t "
'orderreceiver -d[hidden]- dispenseresponder : "   "


'orderresponder -d[hidden]- dispensereceiver
'orderresponder -r[hidden]- dispensereceiver
'orderresponder -r[hidden]- OrderConsumer

'orderplacer -[hidden]r- OrderConsumer : "\t\t\t   "

OrderConsumer -r[hidden]- dispenseconsumer: "\t\t     "

dispensereceiver -r[hidden]- dispenseresponder : "\t\t\t"


OrderConsumer -d- dispensereceiver: "  [[pharm-8.html PHARM-8\nSubmit Dispense]] ↓  "


@enduml