@startuml
skinparam linetype ortho
skinparam linetype polyline

title Medication Actors \n Central Prescription Repository architecture\n


Package "Central Prescription Repository" {
agent "  [[actors-transactions.html#order-placer Order Placer ]]\n(e.g. GP system)" as orderplacer 
agent " [[actors-transactions.html#order-receiver Order Receiver ]]" as orderreceiver 
agent " [[actors-transactions.html#order-receiver Order Responder ]]" as orderresponder 
}
agent "[[actors-transactions.html#OrderConsumer Order Consumer  ]]\n (e.g. Pharmacy)" as OrderConsumer 


'agent "[[actors_and_transactions.html#dipensereceiver Dispense Receiver]]" as dispensereceiver
'agent "[[actors_and_transactions.html#dipenseresponder Dispense Responder]]" as dispenseresponder 

' \n\n   [[PHARM-X2.html PHARM-M2 Supply Response/status]] ↑
orderplacer -r- orderreceiver : " "
orderreceiver -[hidden]r-> orderresponder :" "

'orderresponder -d[hidden]- dispensereceiver
'orderresponder -r[hidden]- dispensereceiver
'orderresponder -r[hidden]- OrderConsumer

'orderplacer -[hidden]r- OrderConsumer :  "      "

'dispensereceiver -l[hidden]- dispenseresponder : "   "



orderresponder -r- OrderConsumer: " "
'OrderConsumer -d- dispensereceiver: "   [[PHARM-X3.html PHARM-X3\nDispense]]↓  "

' → ↑ ← ↓

'orderresponder -r- dispensereceiver:  "   [[PHARM-X2.html PHARM-X2 Dispense]]  ←   "
' dispensereceiver -r- dispenseresponder : ""

'OrderConsumer -d- OrderConsumer : "   [[PHARM-M2.html PHARM-M2 Fetch Orders]] ←  "
'dispenser -[hidden]r- invreporter : "\t\t\t\t\t "
'invreporter -d- invmanager : "   [[PHARM-M5.html PHARM-M5 Inventory Status]] ↑                  \n\n   [[PHARM-M6.html PHARM-M6 Inventory Update]] ↓                 \n\n[[PHARM-M7.html PHARM-M7 Inventory Query]] ↓\t\t  "
@enduml