@startuml
'!include ./style.iuml
skinparam linetype ortho
skinparam linetype polyline

title Prescription Exchange - "Push" architecture
agent "  [[actors-transactions.html#order-placer Order Placer ]]" as orderplacer 

rectangle "Filler/Receiver system" as PS #cee{
  agent " [[actors-transactions.html#order-receiver Order Receiver ]]" as orderreceiver 
  agent " [[actors-transactions.html#order-receiver Order Responder ]]" as orderresponder 
  agent " [[actors-transactions.html#order-consumer Order Consumer   ]]" as OrderConsumer 
}


'agent "[[actors-transactions.html#dispensereceiver Dispense Receiver]]" as dispensereceiver
'agent "[[actors-transactions.html#dispenseresponder Dispense Responder]]" as dispenseresponder 


orderplacer -r- orderreceiver : " [[PHARM-5.html PHARM-5\nSubmit Medication Order]] →  "

orderreceiver -r[hidden]- orderresponder 


'orderreceiver -[hidden]r- orderresponder : "\t\t\t"
orderresponder -u- OrderConsumer



@enduml