@startuml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/font-awesome-5/database.puml

'skinparam linetype ortho
skinparam linetype polyline
hide circle
hide stereotype
hide method

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor #e7fcff
 HeaderBackgroundColor Application
}


class "**Dispense**" as D<<TM>> {
  |_ identifier 0..*   
  |_ patient 1..1   
  |_ receiver 0..1   
  |_ dispenser 1..1   
  |_ relatedRequest 0..*   
  |_ medication 1..1   
  |_ dispensedQuantity 1..1   
  |_ timeOfDispensation 1..1   
  |_ substitution 0..1   
    |_ substitutionOccurred 1..1   
    |_ type 0..1   
    |_ reason 0..1   
  |_ status 1..1   
  |_ statusReason 0..*   
  |_ statusReasonText 0..1   
  |_ usageInstructions 0..*   
  |_ comment 0..*   
}




@enduml
