@startuml
skinparam linetype polyline
hide circle
hide stereotype
hide method

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor #e7fcff
 HeaderBackgroundColor Application
}


class "**IHEMultilineOrder**" as IHEMultilineOrder <<TM>>{
  |_ identifier 1..*   
  |_ patient 1..1   
  |_ prescriber 1..1   
  |_ issueDate 1..1   
  |_ recorder 0..1   
  |_ recordingDate 0..1   
  |_ validFrom 0..1   
  |_ validUntil 0..1   
  |_ medicationLine 1..*   
    |_ status 1..1   
    |_ statusReason 0..*   
    |_ category 0..*   
    |_ basedOn 0..1   
    |_ medication 1..1   
    |_ prescriptionIntent 0..1   
    |_ indication 0..*   
    |_ indicationText 0..1   
    |_ indicationReference 0..*   
    |_ treatmentPeriod 0..1   
    |_ quantityPrescribed 0..1   
    |_ dosageInstructions 0..*   
    |_ preparationInstructions 0..1   
    |_ substitution 0..1   
      |_ allowed[x] 0..1   
      |_ reason[x] 0..1   
    |_ offLabel 0..1   
      |_ isOffLabelUse 1..1   
      |_ reason[x] 0..*   
    |_ repeatsAllowed 0..1   
    |_ minimumDispenseInterval 0..1   
  |_ comment 0..*   
}
@enduml