@startuml
title State transitions of Medication Prescription (Item) in the Hospital subdomain

"Placed" -[#orange]r->[accept]  "In Progress"

"Placed" -[#black]u->[abort]  "Discontinued"


"In Progress" -[#black]u->[abort]  "Discontinued"

"In Progress" -[#green]r->[complete]  "Completed"

"In Progress" -[#cyan]r->[suspend]  "Suspended"


"Suspended" -[#black]u->[abort]  "Discontinued"

"Suspended" -[#green]d->[complete]  "Completed"

"Suspended" -[#blue]d->[resume]  "In Progress"

@enduml