# ╭────────────────────────────────────────────sushi-config.yaml───────────────────────────────────────────────╮
# | documentation of this sushi-config.yaml file https://fshschool.org/docs/sushi/configuration/               |
# ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ihe.pharm.mpd
canonical: http://profiles.ihe.net/PHARM/MPD
name: IHE_MPD
version: 0.1.0
fhirVersion: 5.0.0
status: active
packageId: ihe.pharm.mpd
title: "Medication Prescription and Delivery (MPD)"
description: ImplementationGuide for IHE Pharmacy Medication Prescription and Delivery
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: Integrating the Healthcare Enterprise (IHE)
  url: http://ihe.net
  email: secretary@ihe.net
contact:
  - name: Jose Costa Teixeira
    telecom:
      - system: email
        value: jose.a.teixeira@gmail.com
        use: work
license: CC-BY-SA-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
dependencies:
  ihe.domain.logical-datatypes: current


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - fsh-generated/includes
#  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
#  apply-publisher: 'true'
  apply-version: 'true'
#  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  autoload-resources: 'true'
#  shownav: 'true'

# additional examples that need descriptions
#resources:
#  Bundle/Bundle-FindDocumentReferences:
#    name: Example FindDocumentReferences response
#    description: An example of a searchset Bundle with one DocumentReference
#    exampleBoolean: true

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "IHE MPD (Medication Prescription and Dispense)"
  howtoread.md:
    title: "How to read this publication"
    generation: markdown
  volume-1.md:
    title: "Volume 1"
    generation: markdown
    glossary.md:
      title: "Glossary"
    usecases.md:
      title: "Use Cases"
      presc-use-case-1.md:
        title: "Use Case 1: Order straight to dispense"
      presc-use-case-2.md:
        title: "Use Case 2: Proposal order"
      presc-use-case-3.md:
        title: "Use Case 3: Dispense before prescription"
      presc-use-case-4.md:
        title: "Use Case 4: Change dosage during treatment"
      # MMA-homenursing.md:
      #   title: "Mobile Medication Administration - Home Nursing"
      # MMA-chemotherapy.md:
      #   title: "Mobile Medication Administration - Chemotherapy"
    medication-concepts.md:
      title: "Medication Concepts"
    order-management.md:
      title: "Order Management"
      prescription-lines.md:
        title: "Single- and multiline prescriptions"
      order-statuses.md:
        title: "Managing order status"
    interoperability-model.md:
      title: "Interoperability Model"
    data-models.md:
      title: "Data Models"
    actors-transactions.md:
      title: "Actors and Transactions Overview"
    security.md:
      title: "Security Considerations"   
    cross-profile.md:
      title: "Cross-profile Considerations"   
  example-architectures.md:
    title: "Example implementation architectures"
    generation: markdown

  volume-2.md:
    title: "Volume 2"
    submit-medication-order.md:
      title: "PHARM-X1: Submit Medication Order"
    retrieve-medication-order.md:
      title: "PHARM-X2: Retrieve Medication Orders"
    submit-medication-dispense.md:
      title: "PHARM-X3: Submit Medication Dispense"
    retrieve-medication-dispense.md:
      title: "PHARM-X4: Retrieve Medication Dispenses"
      
    error_codes.md:
      title: "Error Codes"
    testplan.md:
      title: "Test Plan"


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  MPD Home: index.html
  Table of Contents: toc.html
  Volume 1: 
    Overview: volume-1.html
    "Use Cases": usecases.html
    "Medication Concepts": medication-concepts.html
    "Order Management": order-management.html
    "Interoperability Model": interoperability-model.html
    "Data Models": data-models.html
    "Actor and Transactions Overview": actors-transactions.html
    "Security Considerations": security.html
    "Cross-profile Considerations": cross-profile.html
  Volume 2:
    Overview: volume-2.html
    PHARM-X1 - Submit Medication Order: submit-medication-order.html
    PHARM-X2 - Retrieve Medication Order: retrieve-medication-order.html
    PHARM-X3 - Submit Medication Dispense: submit-medication-dispense.html
    PHARM-X4 - Retrieve Medication Dispense: retrieve-medication-dispense.html

  Volume 3:
    "Error Codes": error_codes.html
    "FHIR Maps": fhir_maps.html
  Test Plan: testplan.html
  Artifacts: artifacts.html

