# ╭────────────────────────────────────────────sushi-config.yaml───────────────────────────────────────────────╮
# | documentation of this sushi-config.yaml file https://fshschool.org/docs/sushi/configuration/               |
# ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ihe.pharm.mpd
canonical: http://profiles.ihe.net/PHARM/MPD
name: IHE_MPD
version: 0.1.0
fhirVersion: 5.0.0
status: active
packageId: ihe.pharm.mpd
title: "Medication Prescription and Dispense (MPD)"
description: ImplementationGuide for IHE Pharmacy Medication Prescription and Dispense (MPD) profile
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: Integrating the Healthcare Enterprise (IHE)
  url: http://ihe.net
  email: secretary@ihe.net
contact:
  - name: Jose Costa Teixeira
    telecom:
      - system: email
        value: jose.a.teixeira@gmail.com
        use: work
license: CC-BY-SA-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#dependencies:
#  ihe.domain.logical-datatypes: current


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - fsh-generated/includes
#  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
#  apply-publisher: 'true'
  apply-version: 'true'
#  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  autoload-resources: 'true'
  shownav: 'true'


# additional examples that need descriptions
#resources:
#  Bundle/Bundle-FindDocumentReferences:
#    name: Example FindDocumentReferences response
#    description: An example of a searchset Bundle with one DocumentReference
#    exampleBoolean: true

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md: # FIX MR
    title: "IHE MPD (Medication Prescription and Dispense)"  
  howtoread.md: # If short effort, fix, otherwise remove MR
    title: "How to read this publication"
    generation: markdown
  volume-1.md: # Simplify. What is not possible to simplify - remove JCT
    title: "Volume 1"
    generation: markdown
    glossary.md: # Add only the core actors and concept definitions (prescription vs order, dispense, etc.) JCT
      title: "Glossary" 
    usecases.md: # remove all this and below (unless JCT can do this today / tomorrow) - low pritority JCT
      title: "Use Cases"
      # presc-use-case-1.md:
      #   title: "Use Case 1: Order straight to dispense"
      # presc-use-case-2.md:
      #   title: "Use Case 2: Proposal order"
      # presc-use-case-3.md:
      #   title: "Use Case 3: Dispense before prescription"
      # presc-use-case-4.md:
      #   title: "Use Case 4: Change dosage during treatment"
    medication-concepts.md: # Copy or sumarize from EU MPD (with credits) MR
      title: "Medication Concepts"
    grouping.md: # if not finished, remove and reuse content in above section JCT
      title: "Single- and multiline prescriptions"

#    order-management.md:  # possibly rename, but include key concept (reusing from COW?) - order status, Task, grouping, changes cancellation, ...  JCT can copy COW
#      title: "Order Management"
      # order-statuses.md:
      #   title: "Managing order status"
#    interoperability-model.md: # drop for now 
#      title: "Interoperability Model"
    data-models.md: # update and write simple narrative JCT
      title: "Data Models" 
    actors-transactions.md: # Finish it MR on monday
      title: "Actors and Transactions Overview"
#    security.md: # Copy from somewhere MR
#      title: "Security Considerations"   
#    cross-profile.md: # Add some narrative to say "this is empty for now" JCT
#      title: "Cross-profile Considerations"   
  actor-grouping-examples.md: # Consolidate inside Actors and Transactions Overview MR
    title: "Actor grouping examples"
    generation: markdown

  volume-2.md:
    title: "Volume 2"
    pharm-5.md: # FCFS
      title: "PHARM-5: Submit Medication Order" 
    pharm-7.md: # FCFS
      title: "PHARM-7: Retrieve Medication Orders"
    pharm-8.md: # FCFS
      title: "PHARM-8: Submit Medication Dispense"
    pharm-9.md: # FCFS
      title: "PHARM-9: Retrieve Medication Dispenses"

    error_codes.md:
      title: "Error Codes" # Leave page empty for now
    testplan.md:
      title: "Test Plan" # Leave page empty for now

    usage-examples.md:
      title: "Usage Examples"


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  MPD Home: index.html
  Table of Contents: toc.html
  Volume 1: 
    Overview: volume-1.html
    "Use Cases": usecases.html
    "Medication Concepts": medication-concepts.html
#    "Order Management": order-management.html
#    "Interoperability Model": interoperability-model.html
    "Data Models": data-models.html
    "Actor and Transactions Overview": actors-transactions.html
#    "Security Considerations": security.html
#    "Cross-profile Considerations": cross-profile.html
  Volume 2:
#    Overview: volume-2.html
    PHARM-5 - Submit Medication Order: pharm-5.html
    PHARM-7 - Retrieve Medication Order: pharm-7.html
    PHARM-8 - Submit Medication Dispense: pharm-8.html
    PHARM-9 - Retrieve Medication Dispense: pharm-9.html

#  Volume 3:
#    "Error Codes": error_codes.html
#    "FHIR Maps": fhir_maps.html
  Test Plan: testplan.html
  Artifacts: artifacts.html

