# ╭────────────────────────────────────────────sushi-config.yaml───────────────────────────────────────────────╮
# | documentation of this sushi-config.yaml file https://fshschool.org/docs/sushi/configuration/               |
# ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ihe.mpd
canonical: http://profiles.ihe.net/PHARM/ihe.pharm.mpd
name: IHE_MPD
version: 0.1.0
fhirVersion: 5.0.0
status: active
packageId: ihe.pharm.mpd
title: "Medication Prescription and Delivery (MPD)"
description: ImplementationGuide for IHE Pharmacy Medication Prescription and Delivery
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: Integrating the Healthcare Enterprise (IHE)
  url: http://ihe.net
  email: secretary@ihe.net
contact:
  - name: Jose Costa Teixeira
    telecom:
      - system: email
        value: jose.a.teixeira@gmail.com
        use: work
license: CC-BY-SA-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#dependencies:
#  https://profiles.ihe.net/fhir/ihe.formatcode.fhir: 0.2.4
 
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - fsh-generated/includes
#  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
#  apply-publisher: 'true'
  apply-version: 'true'
#  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  autoload-resources: 'true'
#  shownav: 'true'

# additional examples that need descriptions
#resources:
#  Bundle/Bundle-FindDocumentReferences:
#    name: Example FindDocumentReferences response
#    description: An example of a searchset Bundle with one DocumentReference
#    exampleBoolean: true

# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "MPD Home"
  volume-1.md:
    title: Overview
    generation: markdown
  prescription-lines.md:
    title: "Single- and mutliline prescriptions"
  interoperabilitymodel.md:
    title: "Interoperability Model"
  alternative.md:
    title: "Trial Models"
  medication-concepts.md:
    title: "Medication Concepts"
  usecases.md:
    title: "Use Cases"
    presc-use-case1.md:
      title: "Use Case 1: Order straight to dispense"
    presc-use-case-2.md:
      title: "Use Case 2: Proposal order"
    MMA-homenursing.md:
      title: "Mobile Medication Administration - Home Nursing"
    MMA-chemotherapy.md:
      title: "Mobile Medication Administration - Chemotherapy"
  intro_2.md:
    title: "Introduction to Volume 2"
  error_codes.md:
    title: "Error Codes"
  fhir_maps.md:
    title: "FHIR Maps"
  testplan.md:
    title: "Test Plan"


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  MPD Home: index.html
  Table of Contents: toc.html
  Volume 1: 
    Overview: volume-1.html
    "Trial Models": alternative.html
    "Use Cases": usecases.html
    "Interoperability Model": interoperabilitymodel.html
    "Single- and mutliline prescriptions": prescription-lines.html
    "Medication Concepts": medication-concepts.html
  Volume 2:
    Introduction: intro_2.html
#    "Provide Document Bundle [ITI-65]": ITI-65.html
#    "Find Document Lists [ITI-66]": ITI-66.html
#    "Find Document References [ITI-67]": ITI-67.html
#    "Retrieve Document [ITI-68]": ITI-68.html
  Volume 3:
    "Error Codes": error_codes.html
    "FHIR Maps": fhir_maps.html
  Test Plan: testplan.html
  Artifacts: artifacts.html

