Logical: eHDSIePrescription
Title: "eHDSI ePrescription"
* patient 0..1 Class ""
  * identifier 1..* II "Regional/National Health Identifier" "If the patient has a regional or national Health Identification. This field is required by some national laws"
//    "What does 'required' mean here?"
     
  * personalInformation 0..1 Class ""
//    "What does 'required' mean here?"
    * fullName 1..* EN "The subject's identifying name(s) within the family group or by which the subject is uniquely socially identified [ISO TS 22220]."
      * givenName 1..* ST "Given Name" "The first name of the patient. This field can contain more than one element."
        * ^example.valueString = "Manuel"
      * familyName 1..* ST "Family Name" "The surname/s of the patient. This field can contain more than one element."
    * gender 1..1 CD "Gender" "The gender of the patient. Gender is the biological distinction between male and female [ISO TS 22220]. The gender of the patient may be noted on the prescription since this can be important for gender specific effects of drugs, contra-indications etc."
    * dateOfBirth 1..1 DT "Date of Birth" "The date of birth of the patient. Since age affects drug ADMET (absorption, distribution, metabolism, excretion and toxicity) parameters, this is important for the choice of drug and drug dosage. This field may contain only the year, if day and month are not available."
  * insurance 0..1 Class ""
    * socialorInsuranceNumber 0..1 Untyped "Social/Insurance Number" "If a patient has both Regional /National Health ID and Social /Insurance Number, only the Regional/National Health ID is required by law. If the only identification the patient has is the Social /Insurance Number, then this one is considered as the Regional/National Health ID. This field is required by some national laws"
      * ^comment = "Maps to CDA as identifier" 
  * prescribingHealthProfessional 1..* Class "HP prescribing the medicine"
// Eli, Eli...?
    * identifier 1..* II "HP Identifier" "The identification of the person as health professional (the HP prescribing the medicine to the patient). A unique number or code issued for the purpose of identifying a health care provider [ISO/TS 27527: 2010]; this may be a licence or registration number which can be used to trace the HP and to check whether a drug was prescribed by the right person according to the law."
    * personalInformation 0..1 Class ""
      * fullName 1..1 EN "The subject's identifying name(s) within the family group or by which the subject is uniquely socially identified [ISO TS 22220]."
// Prescribers can only have one name unlike patients.
        * givenName 1..* ST "Given Name" "The first name of the HP prescribing the medicine to the patient. This field can contain more than one element."
          * ^example.valueString = "Oscar"
        * familyName 1..* ST "Family Name" "The surname/s of the HP prescribing the medicine to the patient. This  field  can  contain  more than one element."
      * professionOrSpecialty 1..1 CD "Profession or Specialty" "The profession or field of practice of the HP prescribing the medicine."
        * ^example.valueString = "Dentists"
// This is removed because profession is mandatory so 
//      * medicalSpecialty 0..1 CD "The field of practice /specialization of the HP prescribing the medicine."
//        * ^example.value = "Dermatologist"
    * hpFacilityAddress 1..* AD "HP Facility Address" "The place where the HP prescribing the medicine made the prescription"
// TBD: Why 1..* ?
      * streetAddress 0..1 ST "Street Address" "The street of the place where the HP prescribing the medicine made the prescription."
      * city 0..1 ST "City" "The city of the place where the HP prescribing the medicine made the prescription."
      * postalCode 0..1 ST "ZIP or Postal Code" "The postal code of the place where the HP prescribing the medicine made the prescription"
// ZIP is for USA...
      * stateProvince 0..1 ST "State or Province" "The province of the place where the HP prescribing the medicine made the prescription."
      * country 1..1 ST "Country" "The country where the prescription was made."
      * telephone 0..1 ST "Telephone" 
      * email 0..* ST "E-mail" "The contact e-mail of the facility or of the HP prescribing the medicine."
// At least one of telephone or email is needed
    * organization 1..1 Class "Healthcare provider organization (HCPO)" "The healthcare provider organization of the HP prescribing the medicine."
      * name 1..1 ST "Organization Name" "The name of the healthcare provider organization of the HP prescribing the medicine."
        * ^comment = "Note: This is not a field, but a block of information made up of the following fields. This might not be in the data set, but this information needs to be available for the process traceability."     
// Which fields??
      * identifier 1..1 II "Organization Identifier" "The identification of the healthcare provider organization of the HP prescribing the medicine. This filed can be numbers and/or letters."
* prescriptionClinicalData 1..1 Class "Prescription" "PRESCRIPTION CLINICAL DATA"
  * prescriptionIdentifier 1..1 II "Prescription identifier" "Identification of the prescription."
  * medicinalProduct 0..1 Class ""
    * ^comment = "The attribute can be used to contain the MPID (Medicinal Product Identifier), the EMA PMS ID of the ISO IDMP Standards or an (inter)national equivalent code. Some countries like Denmark and Sweden might have the same medicinal product identifier"
    * medicinalProduct 0..1 Class "Medicinal Product"
      * identifier 0..1 ST "Medicinal Product Identifier" "Identifier of a medicinal product refers to the product inside the package, not the packaged item as such."
      * brandName 0..1 Untyped "Medicinal Product Brand Name" "The name, which may be either an invented name not liable to confusion with the common name, or a common or scientific name accompanied by a trade mark or the name of the marketing authorization holder"
      * Classification 0..1 Untyped "Medicinal Product Classification" "Standardized code corresponding to the product classification"
      * activeIngredients 0..1 Untyped "Active Ingredient(s)" "Substance that alone or in combination with one or more other ingredients produces the intended activity of a medicinal product. Country of treatment translates (does not change) the active ingredient from Country of affiliation to Country of treatment units (single concept), but it is the same active ingredient."
        * substance 0..1 Untyped ""
        * role 0..1 Untyped ""
        * strength 0..1 Untyped ""
        * pharmDoseForm 0..1 Untyped ""
    * package 0..1 Class ""
      * packageDescription 0..1 Untyped ""
      * packageId 0..1 Untyped ""
      * packageType 0..1 Untyped ""
      * packageSize 0..1 Untyped ""
      * package 0..1 Untyped ""
    * routeOfAdministration 0..1 Untyped ""
    * marketingAuthorizationHolder 0..1 Untyped ""
    * substitution 0..1 Untyped ""
    * numberOfPackages 0..1 Untyped ""
    * posology 0..1 Class ""
      * posologyInstructions 0..1 Untyped "" 
      * unitsPerIntake 0..1 Untyped ""
      * frequencyOfIntakes 0..1 Untyped ""
      * timingOfIntakes 0..1 Untyped ""
      * durationOfTreatment 0..1 Untyped ""
* prescriptionData 0..1 Class ""
  * prescription 0..1 Class ""
    * issueDate 0..1 Untyped ""
    * treatmentStart 0..1 Untyped ""
    * treatmentEnd 0..1 Untyped ""
    * patientInstructions 0..1 Untyped ""
    * advicetoDispenser 0..1 Untyped ""
  * legalEntity 0..1 Untyped ""
  * relatedDocument 0..1 Untyped ""







