Logical: ePrescription
Title: "ePrescription"
* patient 0..1 class ""
  * identification 0..1 untyped ""
  * personalInformation 0..1 class ""
    * fullName 0..1 untyped ""
    * gender 0..1 untyped ""
    * dateOfBirth 0..1 untyped ""
  * insurance 0..1 class ""
    * socialorInsuranceNumber 0..1 untyped ""
  * prescriber 0..1 class ""
    * hpIdentification 0..1 class ""
      * identifier 0..1 untyped ""
    * personalInformation 0..1 class ""
      * fullName 0..1 untyped ""
      * profession 0..1 untyped ""
      * medicalSpecialty 0..1 untyped ""
    * practice 0..1 class ""
      * hpFacility 0..1 class ""
        * address 0..1 untyped ""
          * street 0..1 untyped ""
          * city 0..1 untyped ""
          * zip 0..1 untyped ""
          * stateProvince 0..1 untyped ""
          * country 0..1 untyped ""
          * telephone 0..1 untyped ""
          * email 0..1 untyped ""
    * organization 0..1 class ""
      * name 0..1 untyped ""
      * identifier 0..1 untyped ""
* prescription 0..1 class ""
  * prescriptionIdentifier 0..1 untyped ""
  * medicinalProduct 0..1 class ""
    * medicinalProduct 0..1 class ""
      * identifier 0..1 untyped ""
      * brandName 0..1 untyped ""
      * classification 0..1 untyped ""
      * activeIngredients 0..1 untyped ""
      * substance 0..1 untyped ""
      * role 0..1 untyped ""
      * strength 0..1 untyped ""
      * pharmDoseForm 0..1 untyped ""
    * package 0..1 class ""
      * packageDescription 0..1 untyped ""
      * packageId 0..1 untyped ""
      * packageType 0..1 untyped ""
      * packageSize 0..1 untyped ""
      * package 0..1 untyped ""
    * numberOfPackages 0..1 untyped ""
    * posology 0..1 class ""
      * posologyInstructions 0..1 untyped "" 
      * unitsPerIntake 0..1 untyped ""
      * frequencyOfIntakes 0..1 untyped ""
      * timingOfIntakes 0..1 untyped ""
      * durationOfTreatment 0..1 untyped ""
    * routeOfAdministration 0..1 untyped ""
    * substitution 0..1 untyped ""
    * marketingAuthorizationHolder 0..1 untyped ""
* prescriptionData 0..1 class ""
  * prescription 0..1 class ""
    * issueDate 0..1 untyped ""
    * treatmentStart 0..1 untyped ""
    * treatmentEnd 0..1 untyped ""
    * patientInstructions 0..1 untyped ""
    * advicetoDispenser 0..1 untyped ""
  * legalEntity 0..1 untyped ""
  * relatedDocument 0..1 untyped ""







