// Logical: CommonPrescription
// Title: "ePrescription"
// * patient 0..1 Class ""
//   * identifier 1..* II "Regional/National Health Identifier" "If the patient has a regional or national Health Identification. This field is required by some national laws"
//   * personalInformation 0..1 Class ""
//     * fullName 1..* EN "The subject's identifying name(s) within the family group or by which the subject is uniquely socially identified [ISO TS 22220]."
//       * givenName 1..* ST "Given Name" "The first name of the patient. This field can contain more than one element."
//       * familyName 1..* ST "Family Name" "The surname/s of the patient. This field can contain more than one element."
//       * fullTextName 1..* ST "Family Name" "The surname/s of the patient. This field can contain more than one element."
//     * gender 1..1 CD "Gender" "The gender of the patient. Gender is the biological distinction between male and female [ISO TS 22220]. The gender of the patient may be noted on the prescription since this can be important for gender specific effects of drugs, contra-indications etc."
//     * dateOfBirth 1..1 DT "Date of Birth" "The date of birth of the patient. Since age affects drug ADMET (absorption, distribution, metabolism, excretion and toxicity) parameters, this is important for the choice of drug and drug dosage. This field may contain only the year, if day and month are not available."
//   * insurance 0..1 Class ""
//     * socialorInsuranceNumber 0..1 Untyped "Social/Insurance Number" "If a patient has both Regional /National Health ID and Social /Insurance Number, only the Regional/National Health ID is required by law. If the only identification the patient has is the Social /Insurance Number, then this one is considered as the Regional/National Health ID. This field is required by some national laws"
//       * ^comment = "Maps to CDA as identifier" 
//   * prescriber 0..1 Class ""
//     * hpIdentification 0..1 Class ""
//       * identifier 0..1 Untyped ""
//     * personalInformation 0..1 Class ""
//       * fullName 0..1 Untyped ""
//       * profession 0..1 Untyped ""
//       * medicalSpecialty 0..1 Untyped ""
//     * practice 0..1 Class ""
//       * hpFacility 0..1 Class ""
//         * address 0..1 AD ""
//           * street 0..1 Untyped ""
//           * city 0..1 Untyped ""
//           * zip 0..1 Untyped ""
//           * stateProvince 0..1 Untyped ""
//           * country 0..1 Untyped ""
//           * telephone 0..1 Untyped ""
//           * email 0..1 Untyped ""
//     * organization 0..1 Class ""
//       * name 0..1 Untyped ""
//       * identifier 0..1 Untyped ""
// * prescription 0..1 Class ""
//   * prescriptionIdentifier 0..1 Untyped ""
//   * medicinalProduct 0..1 Class ""
//     * medicinalProduct 0..1 Class ""
//       * identifier 0..1 Untyped ""
//       * brandName 0..1 Untyped ""
//       * Classification 0..1 Untyped ""
//       * activeIngredients 0..1 Untyped ""
//       * substance 0..1 Untyped ""
//       * role 0..1 Untyped ""
//       * strength 0..1 Untyped ""
//       * pharmDoseForm 0..1 Untyped ""
//     * package 0..1 Class ""
//       * packageDescription 0..1 Untyped ""
//       * packageId 0..1 Untyped ""
//       * packageType 0..1 Untyped ""
//       * packageSize 0..1 Untyped ""
//       * package 0..1 Untyped ""
//     * numberOfPackages 0..1 Untyped ""
//     * posology 0..1 Class ""
//       * posologyInstructions 0..1 Untyped "" 
//       * unitsPerIntake 0..1 Untyped ""
//       * frequencyOfIntakes 0..1 Untyped ""
//       * timingOfIntakes 0..1 Untyped ""
//       * durationOfTreatment 0..1 Untyped ""
//     * routeOfAdministration 0..1 Untyped ""
//     * substitution 0..1 Untyped ""
//     * marketingAuthorizationHolder 0..1 Untyped ""
// * prescriptionData 0..1 Class ""
//   * prescription 0..1 Class ""
//     * issueDate 0..1 Untyped ""
//     * treatmentStart 0..1 Untyped ""
//     * treatmentEnd 0..1 Untyped ""
//     * patientInstructions 0..1 Untyped ""
//     * advicetoDispenser 0..1 Untyped ""
//   * legalEntity 0..1 Untyped ""
//   * relatedDocument 0..1 Untyped ""







Logical: CommonPrescription
Title: "ePrescription"
* patient 0..1 Class ""
  * identifier 1..* II "Regional/National Health Identifier" "If the patient has a regional or national Health Identification. This field is required by some national laws"
  * personalInformation 0..1 Class ""
    * fullName 1..* EN "The subject's identifying name(s) within the family group or by which the subject is uniquely socially identified [ISO TS 22220]."
      * givenName 1..* ST "Given Name" "The first name of the patient. This field can contain more than one element."
      * familyName 1..* ST "Family Name" "The surname/s of the patient. This field can contain more than one element."
      * fullTextName 1..* ST "Family Name" "The surname/s of the patient. This field can contain more than one element."
    * gender 1..1 CD "Gender" "The gender of the patient. Gender is the biological distinction between male and female [ISO TS 22220]. The gender of the patient may be noted on the prescription since this can be important for gender specific effects of drugs, contra-indications etc."
    * dateOfBirth 1..1 DT "Date of Birth" "The date of birth of the patient. Since age affects drug ADMET (absorption, distribution, metabolism, excretion and toxicity) parameters, this is important for the choice of drug and drug dosage. This field may contain only the year, if day and month are not available."
  * insurance 0..1 Class ""
    * socialorInsuranceNumber 0..1 Untyped "Social/Insurance Number" "If a patient has both Regional /National Health ID and Social /Insurance Number, only the Regional/National Health ID is required by law. If the only identification the patient has is the Social /Insurance Number, then this one is considered as the Regional/National Health ID. This field is required by some national laws"
      * ^comment = "Maps to CDA as identifier" 
  * prescriber 0..1 Class ""
    * hpIdentification 0..1 Class ""
      * identifier 0..1 Untyped ""
    * personalInformation 0..1 Class ""
      * fullName 0..1 Untyped ""
      * profession 0..1 Untyped ""
      * medicalSpecialty 0..1 Untyped ""
    * practice 0..1 Class ""
      * hpFacility 0..1 Class ""
        * address 0..1 AD ""
          * street 0..1 Untyped ""
          * city 0..1 Untyped ""
          * zip 0..1 Untyped ""
          * stateProvince 0..1 Untyped ""
          * country 0..1 Untyped ""
          * telephone 0..1 Untyped ""
          * email 0..1 Untyped ""
    * organization 0..1 Class ""
      * name 0..1 Untyped ""
      * identifier 0..1 Untyped ""
* prescription 0..1 Class ""
  * prescriptionIdentifier 0..1 Untyped ""
  * medicinalProduct 0..1 Class "PrescribedProductModel as a separate model"
  * posology 0..1 Class ""
    * posologyInstructions 0..1 Untyped "" 
    * unitsPerIntake 0..1 Untyped ""
    * frequencyOfIntakes 0..1 Untyped ""
    * timingOfIntakes 0..1 Untyped ""
    * durationOfTreatment 0..1 Untyped ""
    * routeOfAdministration 0..1 Untyped ""
  * substitution 0..1 Untyped "Allowed, not allowed"
* prescriptionData 0..1 Class ""
  * prescription 0..1 Class ""
    * issueDate 0..1 Untyped ""
    * treatmentStart 0..1 Untyped ""
    * treatmentEnd 0..1 Untyped ""
    * patientInstructions 0..1 Untyped ""
    * advicetoDispenser 0..1 Untyped ""
  * legalEntity 0..1 Untyped ""
  * relatedDocument 0..1 Untyped ""







